require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/SubjectStub:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based
  BracesRequiredMethods:
    - 'let'

Style/Documentation:
  Enabled: false

# We can ignore this small performance improvement.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/dummy/db/schema.rb'

# No need to mention StandardError.
Style/RescueStandardError:
  EnforcedStyle: implicit

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false
